"use client"

export interface DemoItem {
  id: number
  title: string
  genre: string
  lyrics: string
}

const defaultDemos: DemoItem[] = [
  {
    id: 1,
    title: "Polaroid Summer",
    genre: "Pop · Nostalgic",
    lyrics: `[Verse 1]
We left our names in the boardwalk grain
Danced through the salt and a midnight rain
Counted the stars as they fell in line
Every wish was yours and mine

[Chorus]
If the summer fades, let the colors stay
Hold the golden hour one more day
When the music stops, I'll still hear the tune
Dancing in the light of a fading moon

[Outro]
I still see us in the light
Burning bright into the night`,
  },
  {
    id: 2,
    title: "Neon Tigers",
    genre: "Rap · Bold",
    lyrics: `[Verse 1]
City lights flicker, I'm painting the sky
Every doubt that I harbored, I kissed it goodbye
Born in the struggle, refined in the flame
They whisper my name, but they don't know the game

[Hook]
Neon tigers, we prowl through the dark
Leaving our mark, igniting the spark
No surrender, no retreat, just the beat of the heart

[Outro]
Roar till the dawn, then we do it again`,
  },
  {
    id: 3,
    title: "Paper Boats",
    genre: "Folk · Reflective",
    lyrics: `[Verse 1]
We folded our dreams into paper boats
Set them afloat where the river bends
Some made it through, some sank like stones
But the river still runs, and the river still knows

[Chorus]
And oh, the water carries what it will
Some things break, some things hold still
I'm learning to let go, learning to trust
The current that carries us

[Outro]
Paper boats, paper boats
Drifting home`,
  },
]

interface GenreGuideProps {
  eyebrow?: string
  title?: string
  description?: string
  demos?: DemoItem[]
}

export default function GenreGuide({
  eyebrow = "DEMO",
  title = "Lyric Generator Demo",
  description = "Real examples generated by our AI — explore the quality and structure for yourself",
  demos = defaultDemos,
}: GenreGuideProps) {
  return (
    <section className="studio-process" style={{ background: "var(--paper)", color: "var(--ink)" }}>
      <div className="studio-shell">
        <div className="studio-section-heading center">
          <span className="studio-eyebrow">{eyebrow}</span>
          <h2>{title}</h2>
          <p>{description}</p>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          {demos.map((demo) => (
            <article
              key={demo.id}
              className="group relative rounded-2xl p-6 border border-[#dceaf2] bg-white/60 backdrop-blur-sm transition-all duration-300 hover:shadow-lg hover:-translate-y-1"
            >
              <header className="mb-4 pb-4 border-b border-[#dceaf2]">
                <p className="text-xs font-mono font-bold tracking-wider text-[#8b5cf6] uppercase mb-1">
                  {demo.genre}
                </p>
                <h3 className="text-lg font-bold text-foreground">{demo.title}</h3>
              </header>
              <div className="lyric-plain text-left">
                {demo.lyrics.split("\n").map((line, i) => (
                  <p key={i} className={line.startsWith("[") ? "font-bold text-[#8b5cf6] mt-3 mb-1 text-sm" : ""}>
                    {line || "\u00A0"}
                  </p>
                ))}
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  )
}
