import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { GeneratorClient } from "@/components/GeneratorClient"
import SubPageShell from "@/components/SubPageShell"
import { genreDemos } from "@/data/genre-demos"
import { getLandingPage, getLandingPageSlugs } from "@/data/landing-pages"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://lyricgenerator.cc"

// Map preset genre to genreDemos keys
const genreToDemoKey: Record<string, string> = {
  Pop: "pop",
  Rock: "rock",
  Rap: "rap",
  "R&B": "rnb",
  Country: "country",
  Jazz: "jazz",
  EDM: "edm",
  "K-Pop": "kpop",
  Folk: "folk",
  Metal: "metal",
  Blues: "blues",
  Indie: "indie",
  Reggae: "reggae",
}

export async function generateStaticParams() {
  return getLandingPageSlugs().map((slug) => ({ slug }))
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const page = getLandingPage(slug)

  if (!page) {
    return { title: "Page Not Found | LyricGenerator.cc" }
  }

  return {
    title: page.title,
    description: page.description,
    keywords: page.keywords,
    openGraph: {
      title: page.title,
      description: page.description,
      type: "website",
      url: `${siteUrl}/${slug}`,
      siteName: "LyricGenerator.cc",
    },
    twitter: {
      card: "summary_large_image",
      title: page.title,
      description: page.description,
    },
    alternates: {
      canonical: `${siteUrl}/${slug}`,
    },
  }
}

export default async function LandingPage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const page = getLandingPage(slug)

  if (!page) {
    notFound()
  }

  const genre = page.preset.genre || ""
  const mood = page.preset.mood || ""
  const genreLabel = genre || "your favorite"
  const moodLabel = mood ? mood.toLowerCase() : ""

  // Resolve demo items for this page's genre
  const demoKey = genreToDemoKey[genre] || "pop"
  const demos = genreDemos[demoKey] || genreDemos["pop"]

  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${siteUrl}/${slug}#webpage`,
        url: `${siteUrl}/${slug}`,
        name: page.title,
        description: page.description,
        isPartOf: { "@id": `${siteUrl}/#website` },
        breadcrumb: { "@id": `${siteUrl}/${slug}#breadcrumb` },
        datePublished: "2024-01-01",
        dateModified: new Date().toISOString().split("T")[0],
        inLanguage: "en-US",
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${siteUrl}/${slug}#breadcrumb`,
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: siteUrl },
          { "@type": "ListItem", position: 2, name: page.h1, item: `${siteUrl}/${slug}` },
        ],
      },
      {
        "@type": "SoftwareApplication",
        name: page.title,
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Any",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
          availability: "https://schema.org/InStock",
        },
        featureList: [
          `${genre || "Multi-genre"} lyrics generation`,
          `${mood || "Multiple"} mood options`,
          "Instant AI generation",
          "Free unlimited use",
          "No signup required",
        ],
        aggregateRating: {
          "@type": "AggregateRating",
          ratingValue: "4.8",
          ratingCount: "12547",
          bestRating: "5",
          worstRating: "1",
        },
      },
      {
        "@type": "FAQPage",
        mainEntity: page.faqItems.map((faq) => ({
          "@type": "Question",
          name: faq.question,
          acceptedAnswer: {
            "@type": "Answer",
            text: faq.answer,
          },
        })),
      },
    ],
  }

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <SubPageShell
        heroKicker={page.heroKicker}
        heroTitle={page.h1}
        heroLede={page.heroLede}
        generatorEyebrow="START CREATING"
        generatorTitle={page.generatorTitle}
        generatorLede={page.generatorLede}
        generator={<GeneratorClient preset={page.preset} />}
        demoEyebrow="LISTEN & LEARN"
        demoTitle={genre ? `${genre} Lyrics Examples & Inspiration` : "Lyrics Examples & Inspiration"}
        demoDescription={`Explore sample ${genreLabel} ${moodLabel ? `and ${moodLabel} ` : ""}lyrics generated by our AI to spark your creativity.`}
        demos={demos}
        bentoTitle={<>{page.bentoTitle}</>}
        bentoLede={page.bentoLede}
        howItWorksTitle={<>{page.howItWorksTitle}</>}
        howItWorksLede={page.howItWorksLede}
        faqItems={page.faqItems}
        finalTitle={page.finalTitle}
        finalLede={page.finalLede}
      />
    </>
  )
}
